/**
 * Guards the two metadata conventions this codebase depends on.
 *
 * Both were violated across eight files simultaneously, and neither failure is
 * visible in local development — you only notice when a link is shared or when
 * someone looks closely at a browser tab.
 *
 * **1. Titles must not hardcode the site suffix.**
 * A layout's `title.template` appends it. Pages that also included it rendered
 * doubled titles: the seller registration tab literally read
 * "Become a Seller | eShop | Seller Dashboard", and `/products` read
 * "Products | eShop | eShop". Three different brand spellings were in use
 * ("eShop", "E-Shop", "E-Commerce Platform"), none of which matched
 * `siteConfig.name`.
 *
 * **2. A page-level `openGraph` block replaces the inherited one wholesale.**
 * Including the share image generated by `app/opengraph-image.tsx`. Verified
 * against a running server: a route declaring `openGraph` emitted zero
 * `og:image` tags, while an otherwise identical route without one emitted the
 * generated image. Several pages declared an `openGraph` that merely restated
 * `title` and `description` — fields Next derives automatically — and paid for
 * it with a blank social preview.
 *
 * The product detail page is the legitimate exception: it overrides with real
 * product photography, which is exactly what a shared product link should show.
 */

import { readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';

const PROJECT_ROOT = join(__dirname, '..', '..', '..');

/**
 * Every route file that can contribute metadata.
 *
 * A hand-rolled walk rather than `fs.globSync`: that is Node 22+, and the
 * installed `@types/node` (20.x) does not declare it, so it fails typecheck
 * even though it runs. A short walk beats pinning the suite to a newer
 * type package.
 */
function routeFiles(): string[] {
  const found: string[] = [];

  const walk = (relativeDir: string): void => {
    for (const entry of readdirSync(join(PROJECT_ROOT, relativeDir), { withFileTypes: true })) {
      const relativePath = relativeDir + '/' + entry.name;
      if (entry.isDirectory()) {
        walk(relativePath);
      } else if (entry.name === 'page.tsx' || entry.name === 'layout.tsx') {
        found.push(relativePath);
      }
    }
  };

  walk('app');
  return found.sort();
}

function read(file: string): string {
  return readFileSync(join(PROJECT_ROOT, file), 'utf8');
}

/**
 * Routes permitted to declare their own `openGraph`.
 *
 * Each entry is a deliberate, reviewed override — not a grandfathered
 * violation. Adding to this list should require justifying why the generic
 * generated share image is wrong for that route.
 */
const OPENGRAPH_OVERRIDE_ALLOWLIST: ReadonlyArray<{ file: string; because: string }> = [
  {
    file: 'app/(public)/products/[slug]/page.tsx',
    because: 'Overrides with real product photography, which is what a shared product link should show.',
  },
  {
    file: 'app/layout.tsx',
    because: 'The root layout defines the inherited defaults every other route builds on.',
  },
];

describe('metadata conventions', () => {
  describe('titles do not hardcode the site suffix', () => {
    it.each(routeFiles())('%s', (file) => {
      const source = read(file);

      // Match a `title:` whose literal contains a pipe — the separator a
      // layout template supplies. `template:` lines are the legitimate place
      // for one, so they are excluded.
      const offenders = source
        .split('\n')
        .map((line, index) => ({ line: line.trim(), number: index + 1 }))
        .filter(
          ({ line }) =>
            /(^|\s)title:\s*['"`]/.test(line) &&
            line.includes('|') &&
            !line.includes('template')
        );

      // Jest has no assertion-message argument, so the failure detail lives in
      // the compared value: a failing diff prints the offending lines verbatim.
      expect({
        file,
        rule: "title must not hardcode the site suffix — the nearest layout's title.template appends it",
        offendingLines: offenders.map((o) => `line ${o.number}: ${o.line}`),
      }).toEqual({
        file,
        rule: "title must not hardcode the site suffix — the nearest layout's title.template appends it",
        offendingLines: [],
      });
    });
  });

  describe('pages do not silently discard the generated share image', () => {
    const allowed = new Set(OPENGRAPH_OVERRIDE_ALLOWLIST.map((entry) => entry.file));

    it.each(routeFiles().filter((f) => !allowed.has(f)))('%s', (file) => {
      const source = read(file);

      // `openGraph:` as a metadata key. A mention inside a comment is fine —
      // several files explain *why* they do not declare one.
      const declaresOpenGraph = /^\s*openGraph:\s*\{/m.test(source);

      expect({
        file,
        rule:
          'a page-level openGraph replaces the inherited one and drops the generated ' +
          'share image; remove it, or add the route to OPENGRAPH_OVERRIDE_ALLOWLIST',
        declaresOpenGraph,
      }).toEqual({
        file,
        rule:
          'a page-level openGraph replaces the inherited one and drops the generated ' +
          'share image; remove it, or add the route to OPENGRAPH_OVERRIDE_ALLOWLIST',
        declaresOpenGraph: false,
      });
    });

    it('documents a reason for every allowed override', () => {
      for (const entry of OPENGRAPH_OVERRIDE_ALLOWLIST) {
        expect(entry.because.length).toBeGreaterThan(20);
      }
    });
  });

  describe('the share image generator exists', () => {
    it('provides an Open Graph image at the app root', () => {
      // Its absence is not a build error — the tags simply vanish, and every
      // shared link silently reverts to a blank preview.
      expect(() => read('app/opengraph-image.tsx')).not.toThrow();
    });

    it('provides a Twitter image that reuses it rather than duplicating it', () => {
      expect(read('app/twitter-image.tsx')).toContain("from './opengraph-image'");
    });
  });
});
