export const PRODUCT_LIMITS = {
  MAX_NAME_LENGTH: 255,
  MAX_DESCRIPTION_LENGTH: 5000,
  MIN_PRICE_CENTS: 1,
  MAX_PRICE_CENTS: 100000000,
  LOW_STOCK_THRESHOLD: 10,
  RATING_MIN: 1,
  RATING_MAX: 5,
} as const;

export type ProductLimits = typeof PRODUCT_LIMITS;
