// next/font/google relies on the Next.js SWC compiler's font-loader plugin,
// which isn't present under plain ts-jest — calling the real export throws.
// Mock it with a shape matching what next/font actually returns at runtime
// (variable/className/style.fontFamily), fallbacks included, so the pure
// helpers in shared/fonts that consume that shape stay genuinely testable.
jest.mock('next/font/google', () => ({
  Inter: jest.fn(() => ({
    variable: '--font-sans',
    className: 'font-sans-mock',
    style: {
      fontFamily:
        'Inter, __Inter_Fallback_abc123, system-ui, -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Helvetica Neue, Arial, sans-serif',
    },
  })),
  JetBrains_Mono: jest.fn(() => ({
    variable: '--font-mono',
    className: 'font-mono-mock',
    style: {
      fontFamily:
        'JetBrains Mono, __JetBrains_Mono_Fallback_abc123, ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, Liberation Mono, Courier New, monospace',
    },
  })),
}));

import {
  fontSans,
  fontMono,
  fontClassNames,
  FONT_CSS_VARIABLES,
  FONT_FALLBACKS,
  tailwindFontConfig,
  validateFonts,
  validateFallbackParity,
} from '@/shared/fonts';

describe('FONT_CSS_VARIABLES', () => {
  it('mirrors the variable names generated by the font loaders', () => {
    expect(FONT_CSS_VARIABLES.sans).toBe(fontSans.variable);
    expect(FONT_CSS_VARIABLES.mono).toBe(fontMono.variable);
  });
});

describe('fontClassNames', () => {
  it('combines both loader class names into a single string', () => {
    expect(fontClassNames).toBe(`${fontSans.variable} ${fontMono.variable}`);
  });
});

describe('FONT_FALLBACKS', () => {
  it('exposes the canonical sans fallback stack', () => {
    expect(FONT_FALLBACKS.sans).toEqual([
      'system-ui',
      '-apple-system',
      'BlinkMacSystemFont',
      'Segoe UI',
      'Roboto',
      'Helvetica Neue',
      'Arial',
      'sans-serif',
    ]);
  });

  it('exposes the canonical mono fallback stack', () => {
    expect(FONT_FALLBACKS.mono).toEqual([
      'ui-monospace',
      'SFMono-Regular',
      'Menlo',
      'Monaco',
      'Consolas',
      'Liberation Mono',
      'Courier New',
      'monospace',
    ]);
  });
});

describe('tailwindFontConfig', () => {
  it('prefixes the sans stack with the CSS variable reference', () => {
    expect(tailwindFontConfig.sans[0]).toBe(`var(${FONT_CSS_VARIABLES.sans})`);
    expect(tailwindFontConfig.sans.slice(1)).toEqual(FONT_FALLBACKS.sans);
  });

  it('prefixes the mono stack with the CSS variable reference', () => {
    expect(tailwindFontConfig.mono[0]).toBe(`var(${FONT_CSS_VARIABLES.mono})`);
    expect(tailwindFontConfig.mono.slice(1)).toEqual(FONT_FALLBACKS.mono);
  });
});

describe('validateFallbackParity', () => {
  const originalNodeEnv = process.env.NODE_ENV;
  let warnSpy: jest.SpyInstance;

  beforeEach(() => {
    warnSpy = jest.spyOn(console, 'warn').mockImplementation(() => {});
  });

  afterEach(() => {
    warnSpy.mockRestore();
    (process.env as { NODE_ENV: string }).NODE_ENV = originalNodeEnv as string;
  });

  it('is a no-op outside development', () => {
    (process.env as { NODE_ENV: string }).NODE_ENV = 'production';
    validateFallbackParity('Inter, system-ui, sans-serif', ['system-ui', 'sans-serif'], 'Inter');
    expect(warnSpy).not.toHaveBeenCalled();
  });

  it('does not warn when the trailing fallbacks match the canonical stack', () => {
    (process.env as { NODE_ENV: string }).NODE_ENV = 'development';
    validateFallbackParity(
      'Inter, __Inter_Fallback_abc123, system-ui, sans-serif',
      ['system-ui', 'sans-serif'],
      'Inter'
    );
    expect(warnSpy).not.toHaveBeenCalled();
  });

  it('warns when the trailing fallbacks diverge from the canonical stack', () => {
    (process.env as { NODE_ENV: string }).NODE_ENV = 'development';
    validateFallbackParity('Inter, Arial, sans-serif', ['system-ui', 'sans-serif'], 'Inter');
    expect(warnSpy).toHaveBeenCalledTimes(1);
    expect(warnSpy.mock.calls[0][0]).toContain('Fallback mismatch detected for "Inter"');
  });
});

describe('validateFonts', () => {
  const originalNodeEnv = process.env.NODE_ENV;
  let warnSpy: jest.SpyInstance;

  beforeEach(() => {
    warnSpy = jest.spyOn(console, 'warn').mockImplementation(() => {});
  });

  afterEach(() => {
    warnSpy.mockRestore();
    (process.env as { NODE_ENV: string }).NODE_ENV = originalNodeEnv as string;
  });

  it('does not throw and stays silent outside development', () => {
    (process.env as { NODE_ENV: string }).NODE_ENV = 'production';
    expect(() => validateFonts()).not.toThrow();
    expect(warnSpy).not.toHaveBeenCalled();
  });

  it('checks both font loaders against their canonical fallback stacks in development', () => {
    (process.env as { NODE_ENV: string }).NODE_ENV = 'development';
    expect(() => validateFonts()).not.toThrow();
  });
});
